### ISSUE TITLE
Control GPIO

### ISSUE THREAD

**Issue by gavrilov** [RyanEwen/esphome-devices#15]
How can I control GPIO (of the screen itself) with widget button without Home Assistant? 

For example, ESP32-2432S028R has
```yaml
output:
  - id: backlight_pwm
    platform: ledc
    pin: 21

light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
```

Can I set `backlight_pwm` or `backlight` to a specific value?
